import {
  GuardadoEn,
  EstadoExpedientes,
  Expediente,
  FormaDePagoTipo,
  HonorariosYSuplidosTipo,
} from "./utils/types";

export const expedients: Expediente = [
  {
    _id: "1",
    orden: "2",
    tipo: "Extrangeria",
    conexiones: "",
    guardadoEn: GuardadoEn.ExpedienteVigente, // ¿?
    responsable: "Mireia",
    codigoCliente: "928",
    codigoClienteProvisional: "123",
    cliente: "Juan Gomez Sierra",
    beneficiario: "Juan",
    asunto: "",
    fechaSolicitudServicioNotificacion: "",
    plazoLegal: "10 dias",
    estado: EstadoExpedientes.Documentacion,
    empresa: "Apple",
    honorarios: 125,
    honorariosYSuplidos: [
      {
        cantidad: 50,
        tipo: HonorariosYSuplidosTipo.RM,
      },
      {
        cantidad: 100,
        tipo: HonorariosYSuplidosTipo.DS,
      },
    ],
    formaDePago: FormaDePagoTipo.Cheque,
    facturado: false,
    comprobadoTodo: false,
  },
  {
    _id: "1",
    orden: "2",
    tipo: "Extrangeria",
    conexiones: "",
    guardadoEn: GuardadoEn.ExpedienteVigente, // ¿?
    responsable: "Mireia",
    codigoCliente: "928",
    codigoClienteProvisional: "123",
    cliente: "Juan Gomez Sierra",
    beneficiario: "Juan",
    asunto: "",
    fechaSolicitudServicioNotificacion: "",
    plazoLegal: "10 dias",
    estado: EstadoExpedientes.Documentacion,
    empresa: "Apple",
    honorarios: 125,
    honorariosYSuplidos: [
      {
        cantidad: 50,
        tipo: HonorariosYSuplidosTipo.RM,
      },
      {
        cantidad: 100,
        tipo: HonorariosYSuplidosTipo.DS,
      },
    ],
    formaDePago: FormaDePagoTipo.Cheque,
    facturado: false,
    comprobadoTodo: false,
  },
  {
    _id: "1",
    orden: "2",
    tipo: "Extrangeria",
    conexiones: "",
    guardadoEn: GuardadoEn.EnCarpeta, // ¿?
    responsable: "Mireia",
    codigoCliente: "928",
    codigoClienteProvisional: "123",
    cliente: "Juan Gomez Sierra",
    beneficiario: "Juan",
    asunto: "",
    fechaSolicitudServicioNotificacion: "",
    plazoLegal: "10 dias",
    estado: EstadoExpedientes.Documentacion,
    empresa: "Apple",
    honorarios: 125,
    honorariosYSuplidos: [
      {
        cantidad: 50,
        tipo: HonorariosYSuplidosTipo.RM,
      },
      {
        cantidad: 100,
        tipo: HonorariosYSuplidosTipo.DS,
      },
    ],
    formaDePago: FormaDePagoTipo.Cheque,
    facturado: false,
    comprobadoTodo: false,
  },
  {
    _id: "1",
    orden: "2",
    tipo: "Extrangeria",
    conexiones: "",
    guardadoEn: GuardadoEn.Fisico, // ¿?
    responsable: "Mireia",
    codigoCliente: "928",
    codigoClienteProvisional: "123",
    cliente: "Juan Gomez Sierra",
    beneficiario: "Juan",
    asunto: "",
    fechaSolicitudServicioNotificacion: "",
    plazoLegal: "10 dias",
    estado: EstadoExpedientes.Documentacion,
    empresa: "Apple",
    honorarios: 125,
    honorariosYSuplidos: [
      {
        cantidad: 50,
        tipo: HonorariosYSuplidosTipo.RM,
      },
      {
        cantidad: 100,
        tipo: HonorariosYSuplidosTipo.DS,
      },
    ],
    formaDePago: FormaDePagoTipo.Cheque,
    facturado: false,
    comprobadoTodo: false,
  },
  {
    _id: "1",
    orden: "2",
    tipo: "Extrangeria",
    conexiones: "",
    guardadoEn: GuardadoEn.Fisico, // ¿?
    responsable: "Mireia",
    codigoCliente: "928",
    codigoClienteProvisional: "123",
    cliente: "Juan Gomez Sierra",
    beneficiario: "Juan",
    asunto: "",
    fechaSolicitudServicioNotificacion: "",
    plazoLegal: "10 dias",
    estado: EstadoExpedientes.Documentacion,
    empresa: "Apple",
    honorarios: 125,
    honorariosYSuplidos: [
      {
        cantidad: 50,
        tipo: HonorariosYSuplidosTipo.RM,
      },
      {
        cantidad: 100,
        tipo: HonorariosYSuplidosTipo.DS,
      },
    ],
    formaDePago: FormaDePagoTipo.Cheque,
    facturado: false,
    comprobadoTodo: false,
  },
];
