version: "3"

services:
  server:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/api
    command: npm run dev
  db:
    image: mongo:6
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    env_file:
      - ./.envs/.local/.mongo
  client:
    build:
      context: ./client
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 80:3000
    depends_on:
      - db
    volumes:
      - ./client:/client
    command: yarn start
volumes:
  mongodb:
