import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { RootState } from "..";
import { SliceState, Expedient } from "../../utils/types";
import { createExpedient, fetchExpedients } from "./API";

export interface ExpedientsState {
  value: {
    count: number;
    page: number;
    size: number;
    data: Expedient[];
  };
  status: SliceState;
}

const initialState: ExpedientsState = {
  value: {
    count: 0,
    page: 0,
    size: 0,
    data: [],
  },
  status: SliceState.Inactive,
};

export const getExpedients = createAsyncThunk(
  "expedients/getExpedients",
  async ({ page, search }: { page?: number; search?: string }) => {
    const response = await fetchExpedients({ page, search });
    return response.data;
  }
);

export const newExpedient = createAsyncThunk(
  "expedients/newExpedient",
  async (expedient) => {
    const response = await createExpedient(expedient);
    return response.data;
  }
);

export const counterSlice = createSlice({
  name: "expedients",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getExpedients.pending, (state) => {
        state.status = SliceState.Loading;
      })
      .addCase(getExpedients.fulfilled, (state, action) => {
        state.status = SliceState.Inactive;
        state.value = action.payload;
      })
      .addCase(getExpedients.rejected, (state) => {
        state.status = SliceState.Failed;
      })
      .addCase(newExpedient.pending, (state) => {
        state.status = SliceState.Loading;
      })
      .addCase(newExpedient.fulfilled, (state, action) => {
        state.status = SliceState.Inactive;
        state.value = {
          ...state.value,
          count: state.value.count + 1,
          data: [action.payload.data, ...state.value],
        };
      })
      .addCase(newExpedient.rejected, (state) => {
        state.status = SliceState.Failed;
      });
  },
});

export const {} = counterSlice.actions;

export const selectExpedients = (state: RootState) => state.expedients.value;

export default counterSlice.reducer;
